[package]
name = "solitude"
version = "0.0.1"
authors = ["Linden", "Asteria", "MooseMan"]
edition = "2021"

[dependencies]
sha2 = "0.10.0"
regex = "1.5.4"
anyhow = "1.0"
data-encoding = "2.1.2"
log = "0.4.14"
tokio-io = "0.1.13"
tokio = { version = "1.15", features = ["full"]}


[dev-dependencies]
env_logger = "0.9.0"
rand = "0.8.4"
